title: "[FIS-55] ACOM-B"
description: "Apostila proprietária e exclusiva de uso do professor Clerisson Nascimento da disciplina física Aplicada 1 do curso ACOM-B"
theme: just-the-docs

url: "https://clerissonmn.github.io"
baseurl: "/acomb-fis55"

#aux_links:
#    Template Repository: https://github.com/just-the-docs/just-the-docs-template

#nav_external_links:
#  - title: "Blog do Prof. Clerisson"
#    url: https://clerissonmn.github.io
#    hide_icon: true

toc: true
    
collections_dir: capitulos
collections:
    ue1_estatica:
        permalink: "/:collection/:title/"
        output: true
        
    ue2_cinematica:
        permalink: "/:collection/:title/"
        output: true
        
just_the_docs:
    collections:
        ue1_estatica:
            name: "U.E.1 Estática"
            nav_fold: true
            
        ue2_cinematica:
            name: "U.E.2 Cinemática"
            nav_fold: true
            
# callouts_opacity: 0.3            
callouts:
  cuidado:
    title: Cuidado
    color: red
    
  cal2:
    title: cal2
    color: grey-lt
    
  exemplo_resolvido:
    title: Exemplo Resolvido
    color: grey-dk
    
  definicao:
    title: Definição
    color: purple
    
  importante:
    title: Importante
    color: blue
    
  note:
    title: Tome Nota
    color: green
    
  cal7:
    title: cal7
    color: yellow
    

    
    