title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
    ue2_cinematica:
        permalink: "/:collection/:path/"
        output: true
        
just_the_docs:
    collections:
        ue2_cinematica:
            name: "U.E.2 Cinemática"
            nav_fold: true