title: "[FIS-55] ACOM-B"
description: "Apostila proprietária e exclusiva de uso do professor Clerisson Nascimento da disciplina física Aplicada 1 do curso ACOM-B"
theme: just-the-docs

url: https://just-the-docs.github.io

#aux_links:
#    Template Repository: https://github.com/just-the-docs/just-the-docs-template

#nav_external_links:
#  - title: "Blog do Prof. Clerisson"
#    url: https://clerissonmn.github.io
#    hide_icon: true
    
collections_dir: capitulos
collections:
    ue1_estatica:
        permalink: "/:collection/:path/"
        output: true
        
    ue2_cinematica:
        permalink: "/:collection/:path/"
        output: true
        
just_the_docs:
    collections:
        ue1_estatica:
            name: "U.E.1 Estática"
            nav_fold: true
            
        ue2_cinematica:
            name: "U.E.2 Cinemática"
            nav_fold: true
            
callouts:
  cal1:
    title: cal1
    color: red
  cal2:
    title: cal2
    color: grey-lt
  cal3:
    title: cal3
    color: grey-dk
  cal4:
    title: cal4
    color: purple
  cal5:
    title: cal5
    color: blue
  cal6:
    title: cal6
    color: green
  cal7:
    title: cal7
    color: yellow

    
    